const ENDPOINTS = {
  AUTH: {
    SIGNUP: '/auth/register',
    VERIFY_EMAIL: '/auth/verify-email',
    LOGIN: '/auth/login',
    FORGOT_PASSWORD: '/auth/forgot-password',
    FORGOT_PASSWORD_VERIFY_EMAIL: '/auth/forgot-password/verify',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH_TOKEN: '/auth/refresh',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  SSO: {
    GOOGLE: '/oauth/google',
    GOOGLE_CALLBACK: '/oauth/google/callback',
  },
  CANDIDATE: {
    PROFILE: '/candidates/profile',
    PROFILE_COMPLETION: '/candidates/profile/completion',
    PROFILE_PHOTO: '/candidates/profile/photo',
    UPDATE_PROFILE: '/candidates/profile',
    UPDATE_EDUCATION: (id: string | number) => `/candidates/education/${id}`,
    UPDATE_EXPERIENCE: (id: string | number) => `/candidates/experiences/${id}`,
    UPDATE_CERTIFICATION: (id: string | number) => `/candidates/certifications/${id}`,
    UPDATE_SKILLS: (skillId: string | number) => `/candidates/skills/${skillId}`,
    ADD_EDUCATION: '/candidates/education',
    GET_EXPERIENCE: '/candidates/experiences',
    ADD_EXPERIENCE: '/candidates/experiences',
    ADD_SKILL: '/candidates/skills',
    ADD_CERTIFICATION: '/candidates/certifications',
    UPDATE_PREFERENCES: '/candidates/preferences',
    SKILLS_LIST: '/skills',
    PROFILE_SKILLS: '/candidates/skills',
    DELETE_EDUCATION: (id: string | number) => `/candidates/education/${id}`,
    DELETE_EXPERIENCE: (id: string | number) => `/candidates/experiences/${id}`,
    DELETE_SKILL: (skillId: string | number) => `/candidates/skills/${skillId}`,
    DELETE_CERTIFICATION: (id: string | number) => `/candidates/certifications/${id}`,
    GET_RESUMES: '/resumes',
    MARK_AS_PRIMARY: (id: string) => `/resumes/${id}/primary`,
    UPLOAD_RESUME: '/resumes/upload',
    DELETE_RESUME: (id: string) => `/resumes/${id}`,
    RESUME_DOWNLOAD: (id: string) => `/resumes/${id}/download-url`,
    DELETE_PROFILE_PHOTO: '/candidates/profile/photo',
  },
  RESUME_VIDEO: {
    PRE_SIGNED_UPLOAD: '/candidates/profile/video/presign-upload',
    CONFIRM_UPLOAD: '/candidates/profile/video/confirm-upload',
    UPLOAD: '/candidates/profile/video',
    UPDATE: '/candidates/profile/video',
    DELETE: '/candidates/profile/video',
    DOWNLOAD: '/candidates/profile/video/download',
  },
  JOBS: {
    TRENDING: '/search/jobs/trending',
    POPULAR: '/search/jobs/popular',
    SEARCH: '/search/jobs',
    DETAILS: (id: string) => `/jobs/${id}`,
    SAVE: (id: string) => `/jobs/${id}/save`,
    RECOMMENDED: '/jobs/recommended',
    SAVED: '/jobs/user/saved',
    GET_FILTERS: '/search/filters',
  },
  APPLICATIONS: {
    APPLY: 'applications',
    QUICK_APPLY: '/applications/quick-apply',
    LIST: '/applications/my-applications',
    WITHDRAW: (id: string) => `/applications/${id}/withdraw`,
    GET_HISTORY: (id: string) => `/applications/${id}/history`,
    ADD_INTERVIEW_FEEDBACK: (id: string) => `/interviews/${id}/candidate-feedback`,
    ANALYTICS: '/applications/analytics/candidate',
  },
  TEMPLATES: {
    LIST: '/resumes/templates',
    TEMPLATE_DATE: '/resumes/template-data',
    GENERATE_PDF: '/resumes/generate-pdf',
  },
  AVATARS: {
    LIST: '/candidates/avatars',
    CHOOSE: '/candidates/profile/avatar',
  },
  MASTER_DATA: {
    DEGRESS: '/degrees',
    FIELDS_OF_STUDY: (degreeId: string) => `/degrees/${degreeId}/fields-of-study`,
    SKILLS: '/skills',
  },
  NOTIFICATIONS: {
    REGISTER: '/notifications/device-token',
    UNREGISTER: '/notifications/device-token',
    LIST: '/notifications',
    GET_UNREAD_COUNT: '/notifications/unread-count',
    DELETE_ALL: '/notifications',
    DELETE_BY_ID: (id: string) => `/notifications/${id}`,
    MARK_ALL_AS_READ: '/notifications/read-all',
    GET_PREFERENCES: '/preferences',
    UPDATE_PREFERENCES: '/preferences',
  },

  EMPLOYER: {
    AUTH: {
      SEND_MOBILE_OTP: '/company/register/send-mobile-otp',
      VERIFY_MOBILE_OTP: '/company/register/verify-mobile-otp',
      SEND_EMAIL_OTP: '/company/register/send-email-otp',
      VERIFY_EMAIL_OTP: '/company/register/verify-email-otp',
      ONBOARDING: {
        USER_DETAILS: '/company/register/basic-details',
        COMPANY_DETAILS: '/company/register/complete',
        GST_PRE_SIGNED_URL: '/company/register/gst-document/upload-url',
      },
    },
    AVATARS: {
      LIST: '/employers/avatars',
      CHOOSE: '/employers/profile/avatar',
    },
    PROFILE: '/employers/profile',
    UPDATE_PROFILE_PHOTO: '/employers/profile/photo',
    UPDATE_PROFILE: '/employers/profile',
    COMPANY_PROFILE: '/company/profile',
    UPDATE_COMPANY_PROFILE: '/company/profile',
    COMPANY_LOGO_UPLOAD: '/company/logo',
    COMPANY_BANNER_UPLOAD: '/company/banner',
    DELETE_PROFILE_PHOTO: '/employers/profile/photo',
    MEMBERS: {
      LIST: '/company-employers',
      CREATE: '/company-employers',
      DETAILS: (id: string) => `/company-employers/${id}`,
      UPDATE: (id: string) => `/company-employers/${id}`,
      DELETE: (id: string) => `/company-employers/${id}`,
    },
    PERMISSIONS: {
      GET_ALL: '/company-employers/permissions',
      PERMISSIONS_BY_MEMBER: (id: string) => `/company-employers/${id}/permissions`,
      UPDATE_PERMISSIONS: (id: string) => `/company-employers/${id}/permissions`,
    },
    GST_DOCUMENT: {
      PRE_SIGNED_URL: '/company/verification-document/upload-url',
      CONFIRM_UPLOAD: '/company/verification-document/confirm',
      DOWNLOAD: '/company/verification-document/url',
    },
    JOBS: {
      LIST: '/jobs/employer/my-jobs',
      CREATE: '/jobs',
      DETAILS: (id: string) => `/jobs/${id}`,
      UPDATE: (id: string) => `/jobs/${id}`,
      DELETE: (id: string) => `/jobs/${id}`,
      CATEGORIES: '/categories/parents',
      SUB_CATEGORIES: (categorId: string) => `/categories/${categorId}/subcategories`,
      ANALYTICS: (id: string) => `/jobs/${id}/analytics`,
      PUBLISH: (id: string) => `/jobs/${id}/publish`,
    },
    APPLICATIONS: {
      ALL: '/applications/employer/all-applications',
      LIST: (jobId: string) => `/applications/job/${jobId}`,
      PROFILE_DETAILS: (id: string) => `/applications/${id}/candidate-profile`,
      DOWNLOAD_RESUME: (id: string) => `/applications/${id}/resume-url`,
      ANALYTICS: '/applications/analytics/employer',
    },
    INTERVIEWS: {
      SCHEDULE: '/interviews',
      LIST: '/interviews/list',
      UPDATE_STATUS: (id: string) => `/applications/${id}/status`,
      UPDATE: (id: string) => `/interviews/${id}`,
      MARK_COMPLETE: (id: string) => `/interviews/${id}/complete`,
      ADD_FEEDBACK: (id: string) => `/interviews/${id}/feedback`,
      CANCEL: (id: string) => `/interviews/${id}/cancel`,
    },
  },

  MESSAGES: {
    THREADS: {
      CREATE: '/messages/threads',
      LIST: '/messages/threads',
      DETAILS: (id: string) => `/messages/threads/${id}`,
      UPDATE: (id: string) => `/messages/threads/${id}`,
      DELETE: (id: string) => `/messages/threads/${id}`,
    },
    CHATS: {
      SEND: (threadId: string) => `/messages/threads/${threadId}/messages`,
      LIST: (threadId: string) => `/messages/threads/${threadId}/messages`,
      UPLOAD_ATTACHMENT: '/messages/attachments/upload-url',
    },
  },

  SUBSCRIPTIONS: {
    GET_ALL: '/subscriptions/plans',
    UPGRADE: '/subscriptions/upgrade',
    USAGE: '/subscriptions/me/usage',
    HISTORY: '/subscriptions/me/history',
  },
};

export default ENDPOINTS;
