export declare const CurrentUser: (...dataOrPipes: unknown[]) => ParameterDecorator;
export declare const UserId: (...dataOrPipes: unknown[]) => ParameterDecorator;
export declare const GetUserRole: (...dataOrPipes: unknown[]) => ParameterDecorator;
export declare const CompanyId: (...dataOrPipes: unknown[]) => ParameterDecorator;
export declare const IpAddress: (...dataOrPipes: unknown[]) => ParameterDecorator;
export declare const UserAgent: (...dataOrPipes: unknown[]) => ParameterDecorator;
export declare const ApiSuccessResponse: (message: string) => (target: any, propertyKey: string, descriptor: PropertyDescriptor) => PropertyDescriptor;
export * from './role.decorator';
export * from './permissions.decorator';
export * from './subscription.decorator';
export * from './public.decorator';
export * from './rate-limit.decorator';
export * from './validation.decorator';
export * from './cache.decorator';
export * from './audit.decorator';
