export declare const frequencyEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["instant", "hourly", "daily", "weekly"]>;
export declare const notificationChannelEnhancedEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["email", "push", "sms", "whatsapp"]>;
export declare const notificationStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["pending", "sent", "delivered", "failed", "bounced"]>;
export declare const queueStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["queued", "processing", "sent", "failed"]>;
export declare const queuePriorityEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["high", "medium", "low"]>;
export declare const notificationPreferencesEnhanced: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "notification_preferences_enhanced";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        notificationType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notification_type";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        emailEnabled: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "email_enabled";
            tableName: "notification_preferences_enhanced";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        pushEnabled: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "push_enabled";
            tableName: "notification_preferences_enhanced";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        smsEnabled: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "sms_enabled";
            tableName: "notification_preferences_enhanced";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        whatsappEnabled: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "whatsapp_enabled";
            tableName: "notification_preferences_enhanced";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        frequency: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "frequency";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "instant" | "daily" | "hourly" | "weekly";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: ["instant", "hourly", "daily", "weekly"];
            baseColumn: never;
        }, {}, {}>;
        quietHoursStart: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "quiet_hours_start";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgTime";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        quietHoursEnd: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "quiet_hours_end";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgTime";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        timezone: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "timezone";
            tableName: "notification_preferences_enhanced";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "notification_preferences_enhanced";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const notificationLogs: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "notification_logs";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        notificationType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notification_type";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        channel: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "channel";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "push" | "email" | "sms" | "whatsapp";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["email", "push", "sms", "whatsapp"];
            baseColumn: never;
        }, {}, {}>;
        recipient: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "recipient";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        subject: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "subject";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        message: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "message";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "pending" | "failed" | "sent" | "delivered" | "bounced";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: ["pending", "sent", "delivered", "failed", "bounced"];
            baseColumn: never;
        }, {}, {}>;
        sentAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "sent_at";
            tableName: "notification_logs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        deliveredAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "delivered_at";
            tableName: "notification_logs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        openedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "opened_at";
            tableName: "notification_logs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        clickedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "clicked_at";
            tableName: "notification_logs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        errorMessage: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "error_message";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        metadata: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "metadata";
            tableName: "notification_logs";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "notification_logs";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const jobAlertsEnhanced: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "job_alerts_enhanced";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "job_alerts_enhanced";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "job_alerts_enhanced";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        name: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "job_alerts_enhanced";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        searchCriteria: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "search_criteria";
            tableName: "job_alerts_enhanced";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        frequency: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "frequency";
            tableName: "job_alerts_enhanced";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "instant" | "daily" | "hourly" | "weekly";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: ["instant", "hourly", "daily", "weekly"];
            baseColumn: never;
        }, {}, {}>;
        channels: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "channels";
            tableName: "job_alerts_enhanced";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "job_alerts_enhanced";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        lastTriggered: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "last_triggered";
            tableName: "job_alerts_enhanced";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "job_alerts_enhanced";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "job_alerts_enhanced";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const notificationQueue: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "notification_queue";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        notificationType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notification_type";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        channel: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "channel";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "push" | "email" | "sms" | "whatsapp";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["email", "push", "sms", "whatsapp"];
            baseColumn: never;
        }, {}, {}>;
        priority: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "priority";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "low" | "medium" | "high";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: ["high", "medium", "low"];
            baseColumn: never;
        }, {}, {}>;
        scheduledFor: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "scheduled_for";
            tableName: "notification_queue";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        payload: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "payload";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "notification_queue";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "failed" | "sent" | "queued" | "processing";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: ["queued", "processing", "sent", "failed"];
            baseColumn: never;
        }, {}, {}>;
        retryCount: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "retry_count";
            tableName: "notification_queue";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "notification_queue";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        processedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "processed_at";
            tableName: "notification_queue";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
