export declare const genderEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["male", "female", "other", "not_specified"]>;
export declare const visibilityEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["public", "private", "semi_private"]>;
export declare const employmentTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["full_time", "part_time", "contract", "internship", "freelance"]>;
export declare const educationLevelEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["high_school", "bachelors", "masters", "phd", "diploma", "certificate"]>;
export declare const skillCategoryEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["technical", "soft", "language", "industry_specific"]>;
export declare const proficiencyLevelEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["beginner", "intermediate", "advanced", "expert"]>;
export declare const fileTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["pdf", "doc", "docx"]>;
export declare const noticePeriodEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["immediate", "15_days", "1_month", "2_months", "3_months"]>;
export declare const jobSearchStatusEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["actively_looking", "open_to_opportunities", "not_looking"]>;
export declare const documentTypeEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["resume", "cover_letter", "certificate", "id_proof", "portfolio", "other"]>;
export declare const workShiftEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["day", "night", "rotational", "flexible"]>;
export declare const profiles: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "profiles";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        userId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "user_id";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        firstName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "first_name";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        middleName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "middle_name";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        lastName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "last_name";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        dateOfBirth: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "date_of_birth";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        gender: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "gender";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "male" | "female" | "other" | "not_specified";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["male", "female", "other", "not_specified"];
            baseColumn: never;
        }, {}, {}>;
        phone: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "phone";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        alternatePhone: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "alternate_phone";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        addressLine1: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "address_line1";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        addressLine2: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "address_line2";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        city: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "city";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        state: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "state";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        country: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "country";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        pinCode: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "pin_code";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        profilePhoto: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_photo";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        professionalSummary: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "professional_summary";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        totalExperienceYears: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "total_experience_years";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        visibility: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "visibility";
            tableName: "profiles";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "public" | "private" | "semi_private";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: ["public", "private", "semi_private"];
            baseColumn: never;
        }, {}, {}>;
        isProfileComplete: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_profile_complete";
            tableName: "profiles";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        completionPercentage: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "completion_percentage";
            tableName: "profiles";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "profiles";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "profiles";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const workExperiences: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "work_experiences";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        companyName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "company_name";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        jobTitle: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "job_title";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        designation: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "designation";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        employmentType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "employment_type";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "full_time" | "part_time" | "contract" | "internship" | "freelance";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["full_time", "part_time", "contract", "internship", "freelance"];
            baseColumn: never;
        }, {}, {}>;
        location: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "location";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isCurrent: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_current";
            tableName: "work_experiences";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        duration: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "duration";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isFresher: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_fresher";
            tableName: "work_experiences";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        startDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "start_date";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        endDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "end_date";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        description: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "description";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        achievements: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "achievements";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        skillsUsed: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "skills_used";
            tableName: "work_experiences";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        displayOrder: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "display_order";
            tableName: "work_experiences";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "work_experiences";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "work_experiences";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const educationRecords: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "education_records";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        level: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "level";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "high_school" | "bachelors" | "masters" | "phd" | "diploma" | "certificate";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["high_school", "bachelors", "masters", "phd", "diploma", "certificate"];
            baseColumn: never;
        }, {}, {}>;
        institution: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "institution";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        degree: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "degree";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        fieldOfStudy: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "field_of_study";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        startDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "start_date";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        endDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "end_date";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        grade: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "grade";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        honors: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "honors";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        relevantCoursework: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "relevant_coursework";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        certificateUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "certificate_url";
            tableName: "education_records";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        displayOrder: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "display_order";
            tableName: "education_records";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "education_records";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "education_records";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const skills: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "skills";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "skills";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        name: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "skills";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        category: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "category";
            tableName: "skills";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "technical" | "soft" | "language" | "industry_specific";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["technical", "soft", "language", "industry_specific"];
            baseColumn: never;
        }, {}, {}>;
        isActive: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "skills";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "skills";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const profileSkills: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "profile_skills";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "profile_skills";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "profile_skills";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        skillId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "skill_id";
            tableName: "profile_skills";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        proficiencyLevel: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "proficiency_level";
            tableName: "profile_skills";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "beginner" | "intermediate" | "advanced" | "expert";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["beginner", "intermediate", "advanced", "expert"];
            baseColumn: never;
        }, {}, {}>;
        yearsOfExperience: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "years_of_experience";
            tableName: "profile_skills";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        displayOrder: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "display_order";
            tableName: "profile_skills";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "profile_skills";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const certifications: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "certifications";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        name: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        issuingOrganization: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "issuing_organization";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        issueDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "issue_date";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expiryDate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "expiry_date";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgDateString";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        credentialId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "credential_id";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        credentialUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "credential_url";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        certificateFile: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "certificate_file";
            tableName: "certifications";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isVerified: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_verified";
            tableName: "certifications";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "certifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "certifications";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const resumes: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "resumes";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        fileName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_name";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        filePath: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_path";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        fileSize: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_size";
            tableName: "resumes";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        fileType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_type";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "pdf" | "doc" | "docx";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["pdf", "doc", "docx"];
            baseColumn: never;
        }, {}, {}>;
        resumeName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "resume_name";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        isDefault: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_default";
            tableName: "resumes";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        isBuiltWithBuilder: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "is_built_with_builder";
            tableName: "resumes";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        templateId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "template_id";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        parsedContent: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "parsed_content";
            tableName: "resumes";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "resumes";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "resumes";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const jobPreferences: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "job_preferences";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        jobTypes: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "job_types";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        preferredLocations: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "preferred_locations";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        willingToRelocate: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "willing_to_relocate";
            tableName: "job_preferences";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expectedSalaryMin: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "expected_salary_min";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        expectedSalaryMax: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "expected_salary_max";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        salaryCurrency: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "salary_currency";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        noticePeriod: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "notice_period";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "immediate" | "15_days" | "1_month" | "2_months" | "3_months";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["immediate", "15_days", "1_month", "2_months", "3_months"];
            baseColumn: never;
        }, {}, {}>;
        preferredIndustries: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "preferred_industries";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        workShift: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "work_shift";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "day" | "night" | "rotational" | "flexible";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["day", "night", "rotational", "flexible"];
            baseColumn: never;
        }, {}, {}>;
        jobSearchStatus: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "job_search_status";
            tableName: "job_preferences";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "actively_looking" | "open_to_opportunities" | "not_looking";
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: ["actively_looking", "open_to_opportunities", "not_looking"];
            baseColumn: never;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "job_preferences";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "job_preferences";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const profileDocuments: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "profile_documents";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "profile_documents";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "profile_documents";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        documentType: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "document_type";
            tableName: "profile_documents";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "cover_letter" | "other" | "certificate" | "resume" | "id_proof" | "portfolio";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: ["resume", "cover_letter", "certificate", "id_proof", "portfolio", "other"];
            baseColumn: never;
        }, {}, {}>;
        fileName: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_name";
            tableName: "profile_documents";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        filePath: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_path";
            tableName: "profile_documents";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
        fileSize: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "file_size";
            tableName: "profile_documents";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        uploadedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "uploaded_at";
            tableName: "profile_documents";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const profileViews: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "profile_views";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "profile_views";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        profileId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "profile_id";
            tableName: "profile_views";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        employerId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "employer_id";
            tableName: "profile_views";
            dataType: "string";
            columnType: "PgUUID";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        viewedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "viewed_at";
            tableName: "profile_views";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            enumValues: undefined;
            baseColumn: never;
        }, {}, {}>;
        source: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "source";
            tableName: "profile_views";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
