export const TECHNICAL_KEYWORDS = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'C#',
  'Ruby',
  'Go',
  'Golang',
  'Rust',
  'PHP',
  'Swift',
  'Kotlin',
  'Scala',
  'R',
  'MATLAB',
  'Perl',
  'Shell',
  'Bash',
  'PowerShell',
  // Frontend
  'React',
  'React.js',
  'ReactJS',
  'Angular',
  'Vue',
  'Vue.js',
  'VueJS',
  'Next.js',
  'NextJS',
  'Nuxt',
  'Svelte',
  'jQuery',
  'HTML',
  'HTML5',
  'CSS',
  'CSS3',
  'SASS',
  'SCSS',
  'LESS',
  'Tailwind',
  'Bootstrap',
  'Material UI',
  'Redux',
  'MobX',
  'Webpack',
  'Vite',
  // Backend
  'Node.js',
  'NodeJS',
  'Express',
  'Express.js',
  'NestJS',
  'Django',
  'Flask',
  'FastAPI',
  'Spring',
  'Spring Boot',
  '.NET',
  'ASP.NET',
  'Ruby on Rails',
  'Rails',
  'Laravel',
  'Symfony',
  // Databases
  'SQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Elasticsearch',
  'DynamoDB',
  'Cassandra',
  'Oracle',
  'SQL Server',
  'SQLite',
  'Firebase',
  'Supabase',
  'GraphQL',
  'Prisma',
  'Sequelize',
  'TypeORM',
  // Cloud & DevOps
  'AWS',
  'Amazon Web Services',
  'Azure',
  'GCP',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'K8s',
  'Jenkins',
  'CircleCI',
  'GitHub Actions',
  'GitLab CI',
  'Terraform',
  'Ansible',
  'Nginx',
  'Apache',
  'Linux',
  'Unix',
  // Data Science & ML
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Data Analysis',
  'Data Science',
  'Data Engineering',
  'Big Data',
  'Hadoop',
  'Spark',
  'Apache Spark',
  'Tableau',
  'Power BI',
  'Excel',
  'Statistics',
  'NLP',
  'Computer Vision',
  'AI',
  'Artificial Intelligence',
  // Mobile
  'iOS',
  'Android',
  'React Native',
  'Flutter',
  'Xamarin',
  'Mobile Development',
  // Tools & Others
  'Git',
  'GitHub',
  'GitLab',
  'Bitbucket',
  'Jira',
  'Confluence',
  'Agile',
  'Scrum',
  'REST',
  'RESTful',
  'API',
  'APIs',
  'Microservices',
  'CI/CD',
  'TDD',
  'Unit Testing',
  'Jest',
  'Mocha',
  'Cypress',
  'Selenium',
  'Postman',
  'VS Code',
  'IntelliJ',
  'Figma',
  'Sketch',
  'Adobe',
  'Photoshop',
  'Illustrator',
  'SAP',
  'Salesforce',
  'CRM',
  'ERP',
  'Blockchain',
  'Web3',
  'Solidity',
];

export const SOFT_KEYWORDS = [
  'Leadership',
  'Communication',
  'Teamwork',
  'Team Player',
  'Collaboration',
  'Problem Solving',
  'Problem-Solving',
  'Analytical',
  'Analysis',
  'Time Management',
  'Critical Thinking',
  'Decision Making',
  'Project Management',
  'Strategic Planning',
  'Strategic Thinking',
  'Creativity',
  'Creative',
  'Innovation',
  'Innovative',
  'Adaptability',
  'Flexibility',
  'Attention to Detail',
  'Detail-Oriented',
  'Organization',
  'Organizational',
  'Presentation',
  'Public Speaking',
  'Negotiation',
  'Conflict Resolution',
  'Customer Service',
  'Client Relations',
  'Interpersonal',
  'Mentoring',
  'Coaching',
  'Training',
  'Research',
  'Writing',
  'Technical Writing',
  'Documentation',
  'Self-Motivated',
  'Initiative',
  'Multitasking',
  'Prioritization',
  'Stakeholder Management',
];
