/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { Receipt, Save, Loader2 } from 'lucide-react';
import http from '@/api/http';
import endpoints from '@/api/endpoints';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';

interface InvoiceConfig {
  platformName: string;
  platformAddress: string;
  platformGstNumber: string;
  platformStateCode: string;
  defaultHsnCode: string;
}

const defaultConfig: InvoiceConfig = {
  platformName: '',
  platformAddress: '',
  platformGstNumber: '',
  platformStateCode: '',
  defaultHsnCode: '',
};

export default function InvoiceSettingsPage() {
  const queryClient = useQueryClient();
  const [formData, setFormData] = useState<InvoiceConfig>(defaultConfig);

  const { data, isLoading } = useQuery({
    queryKey: ['invoice-config'],
    queryFn: async () => {
      const response: any = await http.get(endpoints.platformConfig.invoice);
      return response.data as InvoiceConfig;
    },
  });

  useEffect(() => {
    if (data) {
      setFormData(data);
    }
  }, [data]);

  const updateMutation = useMutation({
    mutationFn: async (config: InvoiceConfig) => {
      return await http.put(endpoints.platformConfig.invoice, config);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoice-config'] });
      toast.success('Invoice settings updated successfully');
    },
    onError: (error: any) => {
      toast.error(error?.message || 'Failed to update settings');
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    updateMutation.mutate(formData);
  };

  const handleChange = (field: keyof InvoiceConfig, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="p-2 bg-primary/10 rounded-lg">
          <Receipt className="h-6 w-6 text-primary" />
        </div>
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Invoice Settings</h1>
          <p className="text-muted-foreground">
            Configure platform details that appear on generated invoices
          </p>
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        <Card>
          <CardHeader>
            <CardTitle>Platform Details</CardTitle>
            <CardDescription>
              These details appear on the "From" section of every invoice generated by the system.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Platform Name */}
            <div className="grid gap-2">
              <Label htmlFor="platformName">Platform / Company Name</Label>
              <Input
                id="platformName"
                placeholder="e.g. AI Job Portal Pvt Ltd"
                value={formData.platformName}
                onChange={(e) => handleChange('platformName', e.target.value)}
              />
              <p className="text-xs text-muted-foreground">
                The legal entity name that appears at the top of the invoice.
              </p>
            </div>

            {/* Platform Address */}
            <div className="grid gap-2">
              <Label htmlFor="platformAddress">Registered Address</Label>
              <Input
                id="platformAddress"
                placeholder="e.g. 123, MG Road, Mumbai, Maharashtra 400001"
                value={formData.platformAddress}
                onChange={(e) => handleChange('platformAddress', e.target.value)}
              />
              <p className="text-xs text-muted-foreground">
                Full registered address including city, state and pincode.
              </p>
            </div>

            <Separator />

            <CardTitle className="text-base">GST Configuration</CardTitle>

            {/* GST Number */}
            <div className="grid gap-2">
              <Label htmlFor="platformGstNumber">GST Number (GSTIN)</Label>
              <Input
                id="platformGstNumber"
                placeholder="e.g. 27AXXXX1234Z1ZA"
                value={formData.platformGstNumber}
                onChange={(e) => handleChange('platformGstNumber', e.target.value.toUpperCase())}
                maxLength={15}
              />
              <p className="text-xs text-muted-foreground">
                15-character GST Identification Number. Leave blank if not GST registered.
              </p>
            </div>

            {/* State Code + HSN Code side by side */}
            <div className="grid md:grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="platformStateCode">State Code</Label>
                <Input
                  id="platformStateCode"
                  placeholder="e.g. 27"
                  value={formData.platformStateCode}
                  onChange={(e) => handleChange('platformStateCode', e.target.value)}
                  maxLength={2}
                />
                <p className="text-xs text-muted-foreground">
                  2-digit state code (e.g. 27 for Maharashtra). Used for CGST/SGST vs IGST split.
                </p>
              </div>

              <div className="grid gap-2">
                <Label htmlFor="defaultHsnCode">Default HSN/SAC Code</Label>
                <Input
                  id="defaultHsnCode"
                  placeholder="e.g. 998314"
                  value={formData.defaultHsnCode}
                  onChange={(e) => handleChange('defaultHsnCode', e.target.value)}
                  maxLength={8}
                />
                <p className="text-xs text-muted-foreground">
                  SAC code for services. Default: 998314 (Online content / IT services).
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="flex justify-end mt-4">
          <Button type="submit" disabled={updateMutation.isPending}>
            {updateMutation.isPending ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Save className="mr-2 h-4 w-4" />
            )}
            Save Changes
          </Button>
        </div>
      </form>
    </div>
  );
}
